insert into tm_iso_codes (code, language) values ('af', 'Afrikaans');
insert into tm_iso_codes (code, language) values ('sq', 'Albanian');
insert into tm_iso_codes (code, language) values ('ar-dz', 'Arabic (Algeria)');
insert into tm_iso_codes (code, language) values ('ar-bh', 'Arabic (Bahrain)');
insert into tm_iso_codes (code, language) values ('ar-eg', 'Arabic (Egypt)');
insert into tm_iso_codes (code, language) values ('ar-iq', 'Arabic (Iraq)');
insert into tm_iso_codes (code, language) values ('ar-jo', 'Arabic (Jordan)');
insert into tm_iso_codes (code, language) values ('ar-kw', 'Arabic (Kuwait)');
insert into tm_iso_codes (code, language) values ('ar-lb', 'Arabic (Lebanon)');
insert into tm_iso_codes (code, language) values ('ar-ly', 'Arabic (Libya)');
insert into tm_iso_codes (code, language) values ('ar-ma', 'Arabic (Morocco)');
insert into tm_iso_codes (code, language) values ('ar-om', 'Arabic (Oman)');
insert into tm_iso_codes (code, language) values ('ar-qa', 'Arabic (Qatar)');
insert into tm_iso_codes (code, language) values ('ar-sa', 'Arabic (Saudi Arabia)');
insert into tm_iso_codes (code, language) values ('ar-sy', 'Arabic (Syria)');
insert into tm_iso_codes (code, language) values ('ar-tn', 'Arabic (Tunisia)');
insert into tm_iso_codes (code, language) values ('ar-ae', 'Arabic (U.A.E.)');
insert into tm_iso_codes (code, language) values ('ar-ye', 'Arabic (Yemen)');
insert into tm_iso_codes (code, language) values ('ar', 'Arabic');
insert into tm_iso_codes (code, language) values ('hy', 'Armenian');
insert into tm_iso_codes (code, language) values ('as', 'Assamese');
insert into tm_iso_codes (code, language) values ('eu', 'Basque');
insert into tm_iso_codes (code, language) values ('be', 'Belarusian');
insert into tm_iso_codes (code, language) values ('bn', 'Bengali');
insert into tm_iso_codes (code, language) values ('bg', 'Bulgarian');
insert into tm_iso_codes (code, language) values ('ca', 'Catalan');
insert into tm_iso_codes (code, language) values ('zh-cn', 'Chinese (China)');
insert into tm_iso_codes (code, language) values ('zh-hk', 'Chinese (Hong Kong SAR)');
insert into tm_iso_codes (code, language) values ('zh-mo', 'Chinese (Macau SAR)');
insert into tm_iso_codes (code, language) values ('zh-sg', 'Chinese (Singapore)');
insert into tm_iso_codes (code, language) values ('zh-tw', 'Chinese (Taiwan)');
insert into tm_iso_codes (code, language) values ('zh', 'Chinese');
insert into tm_iso_codes (code, language) values ('hr', 'Croatian');
insert into tm_iso_codes (code, language) values ('cs', 'Czech');
insert into tm_iso_codes (code, language) values ('da', 'Danish');
insert into tm_iso_codes (code, language) values ('nl-be', 'Dutch (Belgium)');
insert into tm_iso_codes (code, language) values ('nl', 'Dutch (Netherlands)');
insert into tm_iso_codes (code, language) values ('en-au', 'English (Australia)');
insert into tm_iso_codes (code, language) values ('en-bz', 'English (Belize)');
insert into tm_iso_codes (code, language) values ('en-ca', 'English (Canada)');
insert into tm_iso_codes (code, language) values ('en-ie', 'English (Ireland)');
insert into tm_iso_codes (code, language) values ('en-jm', 'English (Jamaica)');
insert into tm_iso_codes (code, language) values ('en-nz', 'English (New Zealand)');
insert into tm_iso_codes (code, language) values ('en-ph', 'English (Philippines)');
insert into tm_iso_codes (code, language) values ('en-za', 'English (South Africa)');
insert into tm_iso_codes (code, language) values ('en-tt', 'English (Trinidad)');
insert into tm_iso_codes (code, language) values ('en-gb', 'English (United Kingdom)');
insert into tm_iso_codes (code, language) values ('en-us', 'English (United States)');
insert into tm_iso_codes (code, language) values ('en-zw', 'English (Zimbabwe)');
insert into tm_iso_codes (code, language) values ('en', 'English');
insert into tm_iso_codes (code, language) values ('et', 'Estonian');
insert into tm_iso_codes (code, language) values ('mk', 'FYRO Macedonian');
insert into tm_iso_codes (code, language) values ('fo', 'Faeroese');
insert into tm_iso_codes (code, language) values ('fa', 'Farsi');
insert into tm_iso_codes (code, language) values ('fi', 'Finnish');
insert into tm_iso_codes (code, language) values ('fr-be', 'French (Belgium)');
insert into tm_iso_codes (code, language) values ('fr-ca', 'French (Canada)');
insert into tm_iso_codes (code, language) values ('fr', 'French (France)');
insert into tm_iso_codes (code, language) values ('fr-lu', 'French (Luxembourg)');
insert into tm_iso_codes (code, language) values ('fr-mc', 'French (Monaco)');
insert into tm_iso_codes (code, language) values ('fr-ch', 'French (Switzerland)');
insert into tm_iso_codes (code, language) values ('gd', 'Gaelic');
insert into tm_iso_codes (code, language) values ('gl', 'Galician');
insert into tm_iso_codes (code, language) values ('de-at', 'German (Austria)');
insert into tm_iso_codes (code, language) values ('de', 'German (Germany)');
insert into tm_iso_codes (code, language) values ('de-li', 'German (Liechtenstein)');
insert into tm_iso_codes (code, language) values ('de-lu', 'German (Luxemgourg)');
insert into tm_iso_codes (code, language) values ('de-ch', 'German (Switzerland)');
insert into tm_iso_codes (code, language) values ('el', 'Greek');
insert into tm_iso_codes (code, language) values ('gu', 'Gujarati');
insert into tm_iso_codes (code, language) values ('he', 'Hebrew');
insert into tm_iso_codes (code, language) values ('hi', 'Hindi');
insert into tm_iso_codes (code, language) values ('hu', 'Hungarian');
insert into tm_iso_codes (code, language) values ('is', 'Icelandic');
insert into tm_iso_codes (code, language) values ('id', 'Indonesian');
insert into tm_iso_codes (code, language) values ('ga', 'Irish');
insert into tm_iso_codes (code, language) values ('it', 'Italian (Italy)');
insert into tm_iso_codes (code, language) values ('it-ch', 'Italian (Switzerland)');
insert into tm_iso_codes (code, language) values ('ja', 'Japanese');
insert into tm_iso_codes (code, language) values ('kn', 'Kannada');
insert into tm_iso_codes (code, language) values ('kk', 'Kazakh');
insert into tm_iso_codes (code, language) values ('kok', 'Konkani');
insert into tm_iso_codes (code, language) values ('ko', 'Korean');
insert into tm_iso_codes (code, language) values ('kz', 'Kyrgyz');
insert into tm_iso_codes (code, language) values ('lv', 'Latvian');
insert into tm_iso_codes (code, language) values ('lt', 'Lithuanian');
insert into tm_iso_codes (code, language) values ('ms', 'Malay (Malaysia)');
insert into tm_iso_codes (code, language) values ('ml', 'Malayalam');
insert into tm_iso_codes (code, language) values ('mt', 'Maltese');
insert into tm_iso_codes (code, language) values ('mr', 'Marathi');
insert into tm_iso_codes (code, language) values ('ne', 'Nepali (India)');
insert into tm_iso_codes (code, language) values ('nb-no', 'Norwegian (Bokmal)');
insert into tm_iso_codes (code, language) values ('no', 'Norwegian (Bokmal)');
insert into tm_iso_codes (code, language) values ('nn-no', 'Norwegian (Nynorsk)');
insert into tm_iso_codes (code, language) values ('or', 'Oriya');
insert into tm_iso_codes (code, language) values ('pl', 'Polish');
insert into tm_iso_codes (code, language) values ('pt-br', 'Portuguese (Brazil)');
insert into tm_iso_codes (code, language) values ('pt', 'Portuguese (Portugal)');
insert into tm_iso_codes (code, language) values ('pa', 'Punjabi');
insert into tm_iso_codes (code, language) values ('ro', 'Romanian');
insert into tm_iso_codes (code, language) values ('ru-md', 'Russian (Moldova)');
insert into tm_iso_codes (code, language) values ('ru', 'Russian');
insert into tm_iso_codes (code, language) values ('sr', 'Serbian');
insert into tm_iso_codes (code, language) values ('sk', 'Slovak');
insert into tm_iso_codes (code, language) values ('sl', 'Slovenian');
insert into tm_iso_codes (code, language) values ('es-ar', 'Spanish (Argentina)');
insert into tm_iso_codes (code, language) values ('es-bo', 'Spanish (Bolivia)');
insert into tm_iso_codes (code, language) values ('es-cl', 'Spanish (Chile)');
insert into tm_iso_codes (code, language) values ('es-co', 'Spanish (Columbia)');
insert into tm_iso_codes (code, language) values ('es-cr', 'Spanish (Costa Rica)');
insert into tm_iso_codes (code, language) values ('es-do', 'Spanish (Dominican Republic)');
insert into tm_iso_codes (code, language) values ('es-ec', 'Spanish (Ecudor)');
insert into tm_iso_codes (code, language) values ('es-sv', 'Spanish (El Salvador)');
insert into tm_iso_codes (code, language) values ('es-gt', 'Spanish (Guatemala)');
insert into tm_iso_codes (code, language) values ('es-hn', 'Spanish (Honduras)');
insert into tm_iso_codes (code, language) values ('es-mx', 'Spanish (Mexico)');
insert into tm_iso_codes (code, language) values ('es-ni', 'Spanish (Nicaragua)');
insert into tm_iso_codes (code, language) values ('es-pa', 'Spanish (Panama)');
insert into tm_iso_codes (code, language) values ('es-py', 'Spanish (Paraguay)');
insert into tm_iso_codes (code, language) values ('es-pe', 'Spanish (Peru)');
insert into tm_iso_codes (code, language) values ('es-pr', 'Spanish (Peurto Rico)');
insert into tm_iso_codes (code, language) values ('es', 'Spanish (Traditional Sort)');
insert into tm_iso_codes (code, language) values ('es-us', 'Spanish (United States)');
insert into tm_iso_codes (code, language) values ('es-uy', 'Spanish (Uruguay)');
insert into tm_iso_codes (code, language) values ('es-ve', 'Spanish (Venezuela)');
insert into tm_iso_codes (code, language) values ('sv-fi', 'Swedish (Finland)');
insert into tm_iso_codes (code, language) values ('sv', 'Swedish');
insert into tm_iso_codes (code, language) values ('ta', 'Tamil');
insert into tm_iso_codes (code, language) values ('te', 'Telugu');
insert into tm_iso_codes (code, language) values ('th', 'Thai');
insert into tm_iso_codes (code, language) values ('tr', 'Turkish');
insert into tm_iso_codes (code, language) values ('uk', 'Ukrainian');
insert into tm_iso_codes (code, language) values ('ur', 'Urdu');
insert into tm_iso_codes (code, language) values ('uz', 'Uzbek');
insert into tm_iso_codes (code, language) values ('vi', 'Vietnamese');
insert into tm_iso_codes (code, language) values ('cy', 'Welsh');
commit;
