insert into tm_languages (code, language, text_direction) values ('af', 'Afrikaans', 'LTR');
insert into tm_languages (code, language, text_direction) values ('sq', 'Albanian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ar-dz', 'Arabic (Algeria)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-bh', 'Arabic (Bahrain)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-eg', 'Arabic (Egypt)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-iq', 'Arabic (Iraq)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-jo', 'Arabic (Jordan)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-kw', 'Arabic (Kuwait)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-lb', 'Arabic (Lebanon)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-ly', 'Arabic (Libya)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-ma', 'Arabic (Morocco)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-om', 'Arabic (Oman)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-qa', 'Arabic (Qatar)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-sa', 'Arabic (Saudi Arabia)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-sy', 'Arabic (Syria)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-tn', 'Arabic (Tunisia)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-ae', 'Arabic (U.A.E.)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar-ye', 'Arabic (Yemen)', 'RTL');
insert into tm_languages (code, language, text_direction) values ('ar', 'Arabic', 'RTL');
insert into tm_languages (code, language, text_direction) values ('hy', 'Armenian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('as', 'Assamese', 'LTR');
insert into tm_languages (code, language, text_direction) values ('eu', 'Basque', 'LTR');
insert into tm_languages (code, language, text_direction) values ('be', 'Belarusian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('bn', 'Bengali', 'LTR');
insert into tm_languages (code, language, text_direction) values ('bg', 'Bulgarian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ca', 'Catalan', 'LTR');
insert into tm_languages (code, language, text_direction) values ('zh-cn', 'Chinese (China)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('zh-hk', 'Chinese (Hong Kong SAR)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('zh-mo', 'Chinese (Macau SAR)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('zh-sg', 'Chinese (Singapore)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('zh-tw', 'Chinese (Taiwan)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('zh', 'Chinese', 'LTR');
insert into tm_languages (code, language, text_direction) values ('hr', 'Croatian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('cs', 'Czech', 'LTR');
insert into tm_languages (code, language, text_direction) values ('da', 'Danish', 'LTR');
insert into tm_languages (code, language, text_direction) values ('nl-be', 'Dutch (Belgium)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('nl', 'Dutch (Netherlands)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-au', 'English (Australia)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-bz', 'English (Belize)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-ca', 'English (Canada)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-ie', 'English (Ireland)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-jm', 'English (Jamaica)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-nz', 'English (New Zealand)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-ph', 'English (Philippines)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-za', 'English (South Africa)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-tt', 'English (Trinidad)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-gb', 'English (United Kingdom)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-us', 'English (United States)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en-zw', 'English (Zimbabwe)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('en', 'English', 'LTR');
insert into tm_languages (code, language, text_direction) values ('et', 'Estonian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('mk', 'FYRO Macedonian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('fo', 'Faeroese', 'LTR');
insert into tm_languages (code, language, text_direction) values ('fa', 'Farsi', 'LTR');
insert into tm_languages (code, language, text_direction) values ('fi', 'Finnish', 'LTR');
insert into tm_languages (code, language, text_direction) values ('fr-be', 'French (Belgium)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('fr-ca', 'French (Canada)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('fr', 'French (France)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('fr-lu', 'French (Luxembourg)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('fr-mc', 'French (Monaco)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('fr-ch', 'French (Switzerland)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('gd', 'Gaelic', 'LTR');
insert into tm_languages (code, language, text_direction) values ('gl', 'Galician', 'LTR');
insert into tm_languages (code, language, text_direction) values ('de-at', 'German (Austria)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('de', 'German (Germany)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('de-li', 'German (Liechtenstein)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('de-lu', 'German (Luxemgourg)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('de-ch', 'German (Switzerland)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('el', 'Greek', 'LTR');
insert into tm_languages (code, language, text_direction) values ('gu', 'Gujarati', 'LTR');
insert into tm_languages (code, language, text_direction) values ('he', 'Hebrew', 'RTL', 'LTR');
insert into tm_languages (code, language, text_direction) values ('hi', 'Hindi', 'LTR');
insert into tm_languages (code, language, text_direction) values ('hu', 'Hungarian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('is', 'Icelandic', 'LTR');
insert into tm_languages (code, language, text_direction) values ('id', 'Indonesian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ga', 'Irish', 'LTR');
insert into tm_languages (code, language, text_direction) values ('it', 'Italian (Italy)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('it-ch', 'Italian (Switzerland)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ja', 'Japanese', 'LTR');
insert into tm_languages (code, language, text_direction) values ('kn', 'Kannada', 'LTR');
insert into tm_languages (code, language, text_direction) values ('kk', 'Kazakh', 'LTR');
insert into tm_languages (code, language, text_direction) values ('kok', 'Konkani', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ko', 'Korean', 'LTR');
insert into tm_languages (code, language, text_direction) values ('kz', 'Kyrgyz', 'LTR');
insert into tm_languages (code, language, text_direction) values ('lv', 'Latvian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('lt', 'Lithuanian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ms', 'Malay (Malaysia)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ml', 'Malayalam', 'LTR');
insert into tm_languages (code, language, text_direction) values ('mt', 'Maltese', 'LTR');
insert into tm_languages (code, language, text_direction) values ('mr', 'Marathi', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ne', 'Nepali (India)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('nb-no', 'Norwegian (Bokmal)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('no', 'Norwegian (Bokmal)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('nn-no', 'Norwegian (Nynorsk)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('or', 'Oriya', 'LTR');
insert into tm_languages (code, language, text_direction) values ('pl', 'Polish', 'LTR');
insert into tm_languages (code, language, text_direction) values ('pt-br', 'Portuguese (Brazil)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('pt', 'Portuguese (Portugal)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('pa', 'Punjabi', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ro', 'Romanian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ru-md', 'Russian (Moldova)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ru', 'Russian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('sr', 'Serbian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('sk', 'Slovak', 'LTR');
insert into tm_languages (code, language, text_direction) values ('sl', 'Slovenian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-ar', 'Spanish (Argentina)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-bo', 'Spanish (Bolivia)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-cl', 'Spanish (Chile)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-co', 'Spanish (Columbia)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-cr', 'Spanish (Costa Rica)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-do', 'Spanish (Dominican Republic)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-ec', 'Spanish (Ecudor)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-sv', 'Spanish (El Salvador)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-gt', 'Spanish (Guatemala)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-hn', 'Spanish (Honduras)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-mx', 'Spanish (Mexico)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-ni', 'Spanish (Nicaragua)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-pa', 'Spanish (Panama)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-py', 'Spanish (Paraguay)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-pe', 'Spanish (Peru)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-pr', 'Spanish (Peurto Rico)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es', 'Spanish (Traditional Sort)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-us', 'Spanish (United States)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-uy', 'Spanish (Uruguay)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('es-ve', 'Spanish (Venezuela)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('sv-fi', 'Swedish (Finland)', 'LTR');
insert into tm_languages (code, language, text_direction) values ('sv', 'Swedish', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ta', 'Tamil', 'LTR');
insert into tm_languages (code, language, text_direction) values ('te', 'Telugu', 'LTR');
insert into tm_languages (code, language, text_direction) values ('th', 'Thai', 'LTR');
insert into tm_languages (code, language, text_direction) values ('tr', 'Turkish', 'LTR');
insert into tm_languages (code, language, text_direction) values ('uk', 'Ukrainian', 'LTR');
insert into tm_languages (code, language, text_direction) values ('ur', 'Urdu', 'RTL');
insert into tm_languages (code, language, text_direction) values ('uz', 'Uzbek', 'LTR');
insert into tm_languages (code, language, text_direction) values ('vi', 'Vietnamese', 'LTR');
insert into tm_languages (code, language, text_direction) values ('cy', 'Welsh', 'LTR');
commit;
