spool tm_db_remove.log


DROP SEQUENCE TM_BACKUP_MESSAGES_SEQ;
DROP SEQUENCE TM_BACKUP_SEQ;
DROP SEQUENCE TM_DOC_MESSAGES_SEQ;
DROP SEQUENCE TM_PREP_MESSAGES_SEQ;
DROP SEQUENCE TM_LANGUAGES_SEQ;

DROP TABLE TM_PREP_MESSAGES;
DROP TABLE TM_DOC_MESSAGES;
DROP TABLE TM_BACKUP_MESSAGES;
DROP TABLE TM_BACKUP; 
DROP TABLE TM_LANGUAGES;

DROP PROCEDURE TM_P_PARSE_CSV;

spool off

exit
